import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import Container from "@/components/Container";
import Link from "next/link";
import Button from "@/components/Button";
import BlogPreview from "@/components/BlogPreview";
import CTA from "@/components/CTA";
import AboutMe from "@/components/AboutMe";
import { sanityClient } from "lib/sanity";
import HeadingH1 from "@/components/headings/HeadingH1";
import Input from "@/components/Input";

export default function Home({ posts }) {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Mont.className}>Hello WOrld</main> */}
      <Layout>
        <Container className="grid px-4 py-8 lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
          <div className="mr-auto place-self-center lg:col-span-7">
            <h1 className="max-w-md mb-4 text-4xl tracking-tight leading-none md:text-5xl xl:text-6xl ">
              Zyklus, Gesundheit, Selbstakzeptanz.
            </h1>
            <p className="max-w-2xl mb-6 font-light lg:mb-8 md:text-lg lg:text-xl ">
              Ein Blog, bei dem sich alles rund um den Zyklus, deine Gesundheit
              und deinem Weg zu mehr Selbstakzeptanz dreht.
            </p>
            <div className="flex lg:w-2/3 w-full sm:flex-row flex-col px-8 sm:space-x-4 sm:space-y-0 space-y-4 sm:px-0 items-end">
              <div className="relative flex-grow w-full">
                <label
                  htmlFor="email"
                  className="leading-7 text-sm text-gray-600 font-medium"
                >
                  Email
                </label>
                <Input
                  className={"lg:min-w-[240px]"}
                  type="email"
                  id="email"
                  name="email"
                />
              </div>
              <Button
                type="submit"
                className="text-white bg-f-green border-0 py-2 px-8 focus:outline-none rounded text-lg"
              >
                Abonnieren
              </Button>
            </div>
          </div>
          <div className="hidden lg:mt-0 lg:col-span-5 lg:flex">
            <Image
              src="/images/woman.webp"
              alt="mockup"
              width={400}
              height={600}
            />
          </div>
        </Container>
        <BlogPreview posts={posts} />
        <AboutMe />
        <CTA />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const posts = await sanityClient.fetch(`*[_type == "post"]`);

  return {
    props: {
      posts,
    },
  };
}
